blank_issues_enabled: false
contact_links:
  - name: Usage Questions (GitHub Discussions)
    url: https://github.com/ilikesql/ilikesql/discussions/new?category=Usage-Questions
    about: Questions and Answers for ilikesql Users 
  - name: Live Chat on Gitter
    url: https://gitter.im/ilikesql/community
    about: Searchable Web-Based Chat
  - name: ilikesql Mailing List
    url: https://groups.google.com/forum/#!forum/ilikesql
    about: Over a decade of questions and answers are here
  - name: Ideas / Feature Proposal (GitHub Discussions)
    url: https://github.com/ilikesql/ilikesql/discussions/new?category=Ideas
    about: Use this for initial discussion for new features and suggestions
  - name: ilikesql Community Guide
    url: https://www.ilikesql.org/support.html
    about: Start here for an overview of ilikesql's support network and posting guidelines

